language: python

cache: pip

notifications:
  email: false

python:
  - "2.7"
  - "3.5"
  - "3.6"

git:
  depth: 3

install:
  - "pip install --upgrade pip wheel" 
  - "pip install --only-binary=numpy,scipy numpy>1.10.0 scipy"
  - "pip install -r requirements.txt"
  - "mkdir mctools"
  - "wget http://major.iric.ca/MajorLabEn/MC-Tools_files/libmccore.dylib.1.6.2"
  - "mv libmccore.dylib.1.6.2 mctools/"
  - "wget http://major.iric.ca/MajorLabEn/MC-Tools_files/MC-Annotate.zip"
  - "unzip MC-Annotate.zip"
  - "mv MC-Annotate mctools/"
  - "export PATH=$PATH:$PWD/mctools/"

before_script:
  - "python setup.py install --user"

script: nose2 test.forgi.test_examples

